blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/TomHilder/lockin/discussions
    about: Ask questions or start a discussion (if discussions are enabled)
